apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: immich-server
  template:
    metadata:
      labels:
        app: immich-server
    spec:
      initContainers:
        - name: init-immich-server
          image: postgres
          command: ['sh', '-c', 'until pg_isready -U "postgres" -h "immich-postgres.immich.svc.cluster.local" -p 5432; do echo waiting for postgres; sleep 2; done']
      containers:
        - name: immich-server
          image: 'ghcr.io/immich-app/immich-server:release'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2283
          envFrom:
          - secretRef:
              name: db-password-secret
          - configMapRef:
              name: immich-configmap
          volumeMounts:
            - mountPath: /usr/src/app/upload
              name: immichdata
          livenessProbe:
            httpGet:
              path: /server-info/ping
              port: 2283
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 5
      volumes:
        - name: immichdata
          persistentVolumeClaim:
            claimName: immich-volume-claim
