apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-model-cache-volume-claim
  labels:
    app: immich-machine-learning
spec:
  storageClassName: hynix-storage-class
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi