apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-postgres-volume-claim
  labels:
    app: immich-postgres
spec:
  storageClassName: hynix-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi