apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-volume-claim
  labels:
    app: immich-server
spec:
  storageClassName: hynix-storage-class
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 250Gi